# Generated by Django 4.1.3 on 2022-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=40)),
                ('dias', models.IntegerField()),
                ('pension', models.CharField(max_length=40)),
            ],
        ),
    ]
