# Generated by Django 4.1.3 on 2022-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_lugar', models.CharField(max_length=40)),
                ('cd_dias', models.IntegerField()),
                ('cd_pension', models.CharField(max_length=40)),
                ('cd_salida', models.DateField()),
                ('cd_regreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Excursiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_lugar', models.CharField(max_length=40)),
                ('e_dias', models.IntegerField()),
                ('e_actividad', models.CharField(max_length=40)),
                ('e_dificultad', models.CharField(max_length=40)),
                ('e_salida', models.DateField()),
                ('e_regreso', models.DateField()),
                ('e_costo', models.BooleanField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_lugar', models.CharField(max_length=40)),
                ('h_dias', models.IntegerField()),
                ('h_pension', models.CharField(max_length=40)),
                ('h_habitacion', models.CharField(max_length=40)),
                ('h_salida', models.DateField()),
                ('h_regreso', models.DateField()),
                ('h_costo', models.BooleanField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='destino',
            old_name='dias',
            new_name='d_dias',
        ),
        migrations.RenameField(
            model_name='destino',
            old_name='lugar',
            new_name='d_lugar',
        ),
        migrations.RenameField(
            model_name='destino',
            old_name='pension',
            new_name='d_pension',
        ),
        migrations.AddField(
            model_name='destino',
            name='d_costo',
            field=models.BooleanField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='d_regreso',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='d_salida',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
