# Generated by Django 4.1.3 on 2022-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_creardestino_excursiones_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_lugar', models.CharField(max_length=40)),
                ('ce_dias', models.IntegerField()),
                ('ce_actividad', models.CharField(max_length=40)),
                ('ce_dificultad', models.CharField(max_length=40)),
                ('ce_salida', models.DateField()),
                ('ce_regreso', models.DateField()),
            ],
        ),
    ]
