# Generated by Django 4.1.3 on 2022-11-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_crearexcursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_lugar', models.CharField(max_length=40)),
                ('ch_dias', models.IntegerField()),
                ('ch_pension', models.CharField(max_length=40)),
                ('ch_habitacion', models.CharField(max_length=40)),
                ('ch_salida', models.DateField()),
                ('ch_regreso', models.DateField()),
            ],
        ),
    ]
