# Generated by Django 4.1.3 on 2022-11-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_crearhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='d_costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
