# Generated by Django 4.1.3 on 2022-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_destino_d_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursiones',
            name='e_costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='h_costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
