# Generated by Django 4.1.3 on 2022-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_excursiones_e_costo_alter_hotel_h_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creardestino',
            old_name='cd_pension',
            new_name='cd_apellido',
        ),
        migrations.RenameField(
            model_name='creardestino',
            old_name='cd_dias',
            new_name='cd_numero',
        ),
        migrations.RemoveField(
            model_name='creardestino',
            name='cd_regreso',
        ),
        migrations.AddField(
            model_name='creardestino',
            name='cd_mail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creardestino',
            name='cd_nombre',
            field=models.CharField(default=12312, max_length=40),
            preserve_default=False,
        ),
    ]
