# Generated by Django 4.1.3 on 2022-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_cd_pension_creardestino_cd_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_nombre', models.CharField(max_length=40)),
                ('sd_apellido', models.CharField(max_length=40)),
                ('sd_numero', models.IntegerField()),
                ('sd_mail', models.CharField(max_length=100)),
                ('sd_lugar', models.CharField(max_length=40)),
                ('sd_salida', models.DateField()),
            ],
        ),
    ]
