# Generated by Django 4.1.3 on 2022-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_hotel_h_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_nombre', models.CharField(max_length=40)),
                ('sh_apellido', models.CharField(max_length=40)),
                ('sh_numero', models.IntegerField()),
                ('sh_mail', models.CharField(max_length=100)),
                ('sh_lugar', models.CharField(max_length=40)),
                ('sh_hotel', models.CharField(max_length=40)),
                ('sh_ingreso', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='h_regreso',
            new_name='h_ingreso',
        ),
    ]
