# Generated by Django 4.1.3 on 2022-11-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_solicitudhotel_rename_h_regreso_hotel_h_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_nombre', models.CharField(max_length=40)),
                ('se_apellido', models.CharField(max_length=40)),
                ('se_numero', models.IntegerField()),
                ('se_mail', models.CharField(max_length=100)),
                ('se_lugar', models.CharField(max_length=40)),
                ('se_actividad', models.CharField(max_length=40)),
                ('se_salida', models.DateField()),
            ],
        ),
    ]
