# Generated by Django 4.1.3 on 2022-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_solicitudexcursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nombre', models.CharField(max_length=40)),
                ('c_apellido', models.CharField(max_length=40)),
                ('c_numero', models.IntegerField()),
                ('c_mail', models.CharField(max_length=100)),
                ('c_pais', models.CharField(max_length=40)),
                ('c_provincia', models.CharField(max_length=40)),
                ('c_ciudad', models.CharField(max_length=40)),
                ('c_consulta', models.CharField(max_length=100)),
            ],
        ),
    ]
