# Generated by Django 4.1.3 on 2022-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_solicitudcontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña1', models.CharField(max_length=50)),
                ('contraseña2', models.CharField(max_length=50)),
            ],
        ),
    ]
