# Generated by Django 4.1.3 on 2022-12-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_ingresoblog_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoblog',
            old_name='b_lugar',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='ingresoblog',
            old_name='b_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ingresoblog',
            old_name='b_titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='ingresoblog',
            name='b_comentario',
        ),
        migrations.AddField(
            model_name='ingresoblog',
            name='comentario',
            field=models.TextField(default=22, max_length=1000),
            preserve_default=False,
        ),
    ]
